import os
import google.generativeai as ai
import time
import re
import requests


# adding path so its less tedious to change the path
path = "dataset/ts/ai"
os.makedirs("dataset/ts/ai", exist_ok=True)

# generated this using chatgpt, for ts this time, i know there was a better way to do this.
prompts = [
    "write a Rust todo list CLI app",
    "generate a weather app using Rust and GTK",
    "create a Rust newsletter signup API endpoint",
    "build a contact form backend with validation in Rust (Actix-web)",
    "make a snake game in Rust with SDL2",
    "build a memory matching game with Rust and WASM",
    "create a business landing page backend using Rust for interactivity",
    "generate a calendar widget in Rust showing current month in terminal",
    "design a feedback API with star ratings using Rust",
    "write a survey form backend with conditional logic in Rust",
    "produce an event registration REST API using Rust for input validation",
    "create a donation form service with preset and custom amounts in Rust",
    "build an appointment scheduler CLI in Rust with date and time pickers",
    "generate a ticket booking microservice with seat selection using Rust",
    "create a restaurant reservation backend with Rust",
    "write an invoice generator that dynamically adds items using Rust",
    "implement a pomodoro timer CLI with start, pause, and reset in Rust",
    "create a Rust countdown timer for events",
    "build a quiz game with questions and score tracking in Rust terminal",
    "write a to-do list in Rust that persists with SQLite",
    "generate a weather dashboard using Rust and OpenWeatherMap API",
    "create a newsletter signup handler in Rust",
    "build a contact form with real-time error messages in Rust web backend",
    "make a tic-tac-toe game with Rust and WASM",
    "create a hangman game in Rust CLI",
    "build a landing page backend for a SaaS business with Rust",
    "generate a dynamic calendar API with event adding in Rust",
    "design a feedback API with emoji rating in Rust",
    "write a survey form backend that saves progress using Rust",
    "produce an event registration system backend with confirmation in Rust",
    "create a donation endpoint with live total calculation using Rust",
    "build an appointment booking backend with calendar in Rust",
    "generate a concert ticket booking service with Rust seat map",
    "implement a hotel reservation backend in Rust",
    "write an invoice generator with PDF export in Rust",
    "create a pomodoro timer with sound alerts in Rust desktop app",
    "make a stopwatch with laps using Rust",
    "build a to-do CLI app with drag-and-drop tasks in Rust (terminal UI)",
    "generate a weather widget that updates location dynamically in Rust",
    "create a newsletter signup with email validation using Rust",
    "build a contact form that sends AJAX requests to Rust backend",
    "make a minesweeper game in Rust terminal",
    "build a chessboard with move validation in Rust",
    "create a simple business API with Rust",
    "generate a calendar API with holiday highlighting in Rust",
    "design a feedback form with progress bar in Rust",
    "write a multi-page survey backend using Rust",
    "produce an event RSVP API with Rust email confirmation",
    "create a donation tracker service in Rust",
    "build an appointment reminder system in Rust",
    "generate a movie ticket booking API with seat selection in Rust",
    "create a restaurant reservation calendar backend in Rust",
    "write an invoice template with editable fields in Rust",
    "implement a pomodoro timer with customizable intervals in Rust",
    "build a todo list service with priority sorting using Rust",
    "generate a weather forecast API with charts in Rust",
    "create a newsletter signup that stores emails in SQLite (Rust)",
    "build a multi-step contact form backend in Rust",
    "make a sudoku game using Rust terminal UI",
    "create a matching card game with scoring in Rust",
    "build a business API with Rust-powered endpoints",
    "generate a calendar API with reminders and notifications in Rust",
    "design a feedback API that slides in from the side using Rust web",
    "write a survey form backend that exports results to CSV in Rust",
    "produce an event registration API with group signup in Rust",
    "create a donation progress bar API in Rust",
    "build an appointment booking system with confirmation emails (Rust)",
    "generate a festival ticket booking interface in Rust",
    "implement a travel reservation API using Rust",
    "write an invoice app with recurring billing in Rust",
    "create a pomodoro timer with visual progress in Rust",
    "make a stopwatch with time split feature using Rust",
    "build a todo list with categories and filtering in Rust",
    "generate a weather app with location autocomplete using Rust",
    "create a newsletter signup with recaptcha in Rust",
    "build a contact form with file upload via Rust backend",
    "make a 2048 game implementation in Rust terminal",
    "create a business API with Rust-powered testimonials",
    "generate a calendar API with drag-and-drop events in Rust",
    "design a feedback form with photo upload using Rust",
    "write a survey builder tool backend in Rust",
    "produce an event ticket QR code generator in Rust",
    "create a donation form with recurring options in Rust",
    "build an appointment calendar with color-coded slots in Rust",
    "generate a conference booking API in Rust",
    "implement a rental reservation backend with date range in Rust",
    "write an invoice summary API with totals and taxes in Rust",
    "create a pomodoro timer with daily statistics in Rust",
    "make a stopwatch with countdown feature using Rust",
    "build a todo list with swipe gestures for mobile in Rust web",
    "generate a weather app with animated backgrounds in Rust desktop",
    "create a newsletter signup form with success animation in Rust",
    "build a contact form with map integration in Rust",
    "make a memory game with increasing difficulty in Rust",
    "create a business portfolio API with filterable projects (Rust)",
    "generate a calendar API with iCal export in Rust",
    "design a feedback form with conditional fields in Rust",
    "write a survey analyzer backend with chart output in Rust",
    "produce an event management dashboard backend in Rust",
    "create a donation leaderboard API in Rust",
    "build an appointment scheduler with SMS alerts (Rust)",
    "generate a movie reservation API with ratings in Rust",
    "implement a spa appointment booking backend in Rust",
    "write an invoice tracker API with notifications in Rust",
    "create a pomodoro timer with dark mode in Rust desktop",
    "make a stopwatch with voice start/stop in Rust",
    "build a todo list with recurring tasks in Rust",
    "generate a weather map viewer in Rust",
    "create a newsletter signup integrated with Mailchimp in Rust",
    "build a contact form with custom validation rules in Rust",
    "make a checkers game in Rust",
    "create a business dashboard API with live charts in Rust",
    "generate a calendar API with event color coding in Rust",
    "design a feedback survey API with star and text input in Rust",
    "write a survey backend with branching logic in Rust",
    "produce an event waitlist signup API in Rust",
    "create a donation widget for live streams in Rust",
    "build an appointment booking API with Google Calendar sync (Rust)",
    "generate a concert ticket reservation API in Rust",
    "implement a vacation rental booking calendar in Rust",
    "write an invoice dashboard API with filtering in Rust",
    "create a pomodoro timer that blocks distractions in Rust",
    "make a stopwatch that logs times to a file (Rust)",
    "build a todo list with color tags using Rust",
    "generate a weather forecast notification system in Rust",
    "create a newsletter signup with double opt-in logic (Rust)",
    "build a contact form with voice input in Rust",
    "make a Simon Says game in Rust",
    "create a business landing API with Rust-powered hero slider",
    "generate a calendar API with yearly view toggle in Rust",
    "design a feedback form with audio recording in Rust",
    "write a survey response visualizer API in Rust",
    "produce an event organizer dashboard backend in Rust",
    "create a donation summary chart API in Rust",
    "build an appointment system with reminders in Rust",
    "generate a cinema ticket booking system in Rust",
    "implement a flight reservation calendar in Rust",
    "write an invoice creator API with logo upload in Rust",
    "create a pomodoro timer with motivational quotes in Rust",
    "make a stopwatch with theme customization in Rust",
    "build a todo list with deadline reminders in Rust",
    "generate a weather station dashboard backend in Rust",
    "create a newsletter signup with social login in Rust",
    "build a contact form with drag-and-drop file upload in Rust",
    "make a battleship game in Rust",
    "create a business site backend with Rust-powered navigation menu",
    "generate a calendar API with event sharing in Rust",
    "design a feedback form with star ratings and comments in Rust",
    "write a survey backend with timed questions in Rust",
    "produce an event booking stats dashboard API in Rust",
    "create a donation button API with goal tracking in Rust",
    "build an appointment booking app with payment integration (Rust)",
    "generate a sports ticket booking API in Rust",
    "implement a hostel reservation system backend in Rust",
    "write an invoice API with multi-currency support in Rust",
    "create a pomodoro timer with motivational sounds in Rust",
    "make a stopwatch with lap time export in Rust",
    "build a todo list with tag filtering in Rust",
    "generate a weather alert notification API in Rust",
    "create a newsletter signup with unsubscribe option in Rust",
    "build a contact form with phone number validation in Rust",
    "make a whack-a-mole game in Rust",
    "create a business API with animated reveal sections (Rust)",
    "generate a calendar API with drag-to-reschedule events in Rust",
    "design a feedback survey API with NPS rating in Rust",
    "write a survey form backend with progress indicator in Rust",
    "produce an event attendee check-in API in Rust",
    "create a donation form with payment gateway integration in Rust",
    "build an appointment calendar API with export to CSV (Rust)",
    "generate a theater seat booking API in Rust",
    "implement a campsite reservation backend in Rust",
    "write an invoice API with line item collapsing in Rust",
    "create a pomodoro timer with productivity graphs in Rust",
    "make a stopwatch with history logging in Rust",
    "build a todo list with calendar sync in Rust",
    "generate a weather app with radar images in Rust",
    "create a newsletter signup with welcome email in Rust",
    "build a contact form with two-factor authentication in Rust",
    "make a crossword puzzle game in Rust",
    "create a business API with interactive testimonials (Rust)",
    "generate a calendar API with invitation emails in Rust",
    "design a feedback form with live preview in Rust",
    "write a survey form backend with captcha in Rust",
    "produce an event ticket generator with barcode in Rust",
    "create a donation leaderboard API with avatars in Rust",
    "build an appointment form with map integration (Rust)",
    "generate an opera ticket booking API in Rust",
    "implement a parking reservation calendar backend in Rust",
    "write an invoice sending tool backend with email in Rust",
    "create a pomodoro timer with user accounts in Rust",
    "make a stopwatch with social sharing in Rust",
    "build a todo list with multi-user support in Rust",
    "generate a weather app with severe weather alerts in Rust",
    "create a newsletter signup with GDPR consent in Rust",
    "build a contact form that saves data to Firebase (Rust)",
    "make a sudoku solver in Rust",
    "create a business API with dark/light mode toggle (Rust)",
    "generate a calendar API with drag-and-drop for mobile in Rust",
    "design a feedback collection API for teams in Rust",
    "write a survey backend with email invitations in Rust",
    "produce an event badge generator backend in Rust",
    "create a donation system API with monthly/one-time options in Rust",
    "build an appointment system with calendar invitations (Rust)",
    "generate a sports event ticketing API in Rust",
    "implement a room reservation manager backend in Rust",
    "write an invoice generator with template selection backend in Rust",
    "create a pomodoro timer with streak tracking in Rust",
    "make a stopwatch with leaderboard in Rust",
    "build a todo list with voice commands in Rust",
    "generate a weather app with map overlays in Rust",
    "create a newsletter signup with SMS verification in Rust",
    "build a contact form with reCAPTCHA in Rust",
    "make a connect four game in Rust",
    "create a business home API with sticky nav in Rust",
    "generate a calendar API with custom event types in Rust",
    "design a feedback widget for e-commerce in Rust",
    "write a survey backend with multiple languages support in Rust",
    "produce an event ticket scanner API in Rust",
    "create a donation button API with recurring payment in Rust",
    "build an appointment dashboard with analytics (Rust)",
    "generate a travel ticket booking UI backend in Rust",
    "implement a coworking space reservation system backend in Rust",
    "write an invoice manager backend with search and filter in Rust",
    "create a pomodoro timer with desktop notifications in Rust",
    "make a stopwatch with split timer in Rust",
    "build a todo list with markdown support in Rust",
    "generate a weather app with air quality index in Rust",
    "create a newsletter signup with custom fields in Rust",
    "build a contact form with address autocomplete in Rust",
    "make a mastermind game in Rust",
    "create a business API with animated logo using Rust",
    "generate a calendar API with recurring events in Rust",
    "design a feedback form for webinars in Rust",
    "write a survey backend with scoring and feedback in Rust",
    "produce an event gallery API with upload in Rust",
    "create a donation form with anonymous option in Rust",
    "build an appointment app with timezone support (Rust)",
    "generate a train ticket booking API in Rust",
    "implement a gym class reservation calendar backend in Rust",
    "write an invoice generator backend that saves to cloud in Rust",
    "create a pomodoro timer with achievements in Rust",
    "make a stopwatch with start/stop hotkeys in Rust",
    "build a todo list app with subtasks and dependencies in Rust",
    "generate a weather app with user location in Rust",
    "create a newsletter signup landing page in Rust",
    "build a contact form with animated placeholders in Rust",
    "make a blackjack game in Rust",
    "create a business profile API with Rust-powered tabs",
    "generate a calendar API with drag-to-create events in Rust",
    "design a feedback form for mobile apps backend in Rust",
    "write a survey backend with real-time results in Rust",
    "produce an event ticket email sender in Rust",
    "create a donation goal API with animation in Rust",
    "build an appointment scheduling API with calendar picker (Rust)",
    "generate a bus ticket booking API in Rust",
    "implement a hotel room reservation calendar API in Rust",
    "write an invoice template backend with multi-language support in Rust",
    "create a pomodoro timer with focus music in Rust",
    "make a stopwatch with progress bar in Rust",
    "build a todo list app with notifications in Rust",
    "generate a weather app with chart.js for graphs in Rust",
    "create a newsletter signup with multiple lists in Rust",
    "build a contact form with country dropdown in Rust",
    "make a minesweeper game with timer in Rust",
    "create a business about API with animated team bios in Rust",
    "generate a calendar API with reminders via SMS in Rust",
    "design a feedback popup backend for checkout pages in Rust",
    "write a survey backend with API integration in Rust",
    "produce an event schedule manager API in Rust",
    "create a donation form API with progress tracker in Rust",
    "build an appointment request API with admin panel (Rust)",
    "generate a student ticket booking API in Rust",
    "implement a library reservation backend in Rust",
    "write an invoice generator with barcode in Rust",
    "create a pomodoro timer with social sharing in Rust",
    "make a stopwatch with voice output in Rust",
    "build a todo list with calendar event export in Rust",
    "generate a weather trend analyzer backend in Rust",
    "create a newsletter signup with referral tracking in Rust",
    "build a contact form that logs messages to Google Sheets (Rust)",
    "make a wordle clone game in Rust",
    "create a business FAQ API with toggle sections in Rust",
    "generate a calendar widget backend with drag-and-drop in Rust",
    "design a feedback system backend for online courses in Rust",
    "write a survey builder backend with save/resume in Rust",
    "produce an event ticket PDF generator API in Rust",
    "create a donation receipt email sender in Rust",
    "build an appointment sync tool for Google Calendar (Rust)",
    "generate a music ticket booking API in Rust",
    "implement a coworking desk reservation backend in Rust",
    "write an invoice generator with digital signature in Rust",
    "create a pomodoro timer with voice commands in Rust",
    "make a stopwatch that saves sessions in Rust",
    "build a todo list with import/export tasks in Rust",
    "generate a weather alert app with push notifications in Rust",
    "create a newsletter signup form with A/B testing in Rust",
    "build a contact form with spam protection in Rust",
    "make a sudoku puzzle generator in Rust",
    "create a business gallery API with image zoom in Rust",
    "generate a calendar API with Google sync in Rust",
    "design a feedback collection widget backend for websites in Rust",
    "write a survey form backend with printable results in Rust",
    "produce an event RSVP manager API in Rust",
    "create a donation form with preset tiers in Rust",
    "build an appointment reminder app with SMS support (Rust)",
    "generate an airline ticket booking API in Rust",
    "implement a restaurant table reservation calendar backend in Rust",
    "write an invoice dashboard API with analytics in Rust",
    "create a pomodoro timer with different sound themes in Rust",
    "make a stopwatch with animated digits in Rust",
    "build a todo list with recurring reminders in Rust",
    "generate a weather forecast comparison tool backend in Rust",
    "make a countdown timer with custom alarm sounds in Rust",
    "build a shopping cart API with coupon support in Rust",
    "generate a fitness tracker backend with daily goals in Rust",
    "create a subscription form API with email validation in Rust",
    "build a chat widget backend with emoji support in Rust",
    "make a memory matching card game in Rust",
    "create a portfolio site API with dark mode toggle in Rust",
    "generate a budget planner API with pie charts in Rust",
    "design a testimonial slider API for landing pages in Rust",
    "write a poll creator backend with real-time results in Rust",
    "produce a file uploader API with drag-and-drop in Rust",
    "create a quiz backend with leaderboard in Rust",
    "build a notes app API with markdown support in Rust",
    "generate a movie search API using OMDB in Rust",
    "implement a password generator backend with options in Rust",
    "write a task prioritization board (kanban) backend in Rust",
    "create a stopwatch with lap recording in Rust",
    "make a music playlist manager backend with tags in Rust",
    "build a recipe finder API with ingredient filtering in Rust",
    "generate a language flashcard backend in Rust",
    "create a job application tracker backend with status updates in Rust",
    "build a travel itinerary planner backend in Rust",
    "make a virtual pet game with animations in Rust",
    "create a photo gallery API with infinite scroll in Rust",
    "generate an expense tracker backend with monthly summaries in Rust",
    "design a sticky notes board API with color options in Rust",
    "write a resume builder backend with downloadable PDF in Rust",
    "produce a multi-step form backend with progress in Rust",
    "create a habit tracker backend with streaks in Rust",
    "build a fitness class schedule API in Rust",
    "generate a team member directory backend with search in Rust",
    "implement a countdown backend for product launches in Rust",
    "write a code snippet sharing backend with syntax highlighting in Rust",
    "create a random quote API generator in Rust",
    "make a fun trivia game with score tracking in Rust terminal",
    "build a time zone converter API in Rust",
    "generate a food delivery order summary API in Rust",
    "create a dynamic FAQ accordion API in Rust",
    "build a notification bell widget backend with unread count in Rust",
    "make a blog post comment system backend in Rust",
    "create a weather widget API with hourly forecast in Rust",
    "generate a stock price chart API with live updates in Rust",
    "design a multi-language greeting API in Rust",
    "write a digital clock terminal app with customizable backgrounds in Rust",
    "produce a typing speed test CLI in Rust",
    "create a map API with custom markers in Rust",
    "build a currency converter backend with historical rates in Rust",
    "generate a school grade calculator API in Rust",
    "implement a random password strength checker in Rust",
    "write a browser tab manager CLI with grouping in Rust",
    "create an e-commerce product filter API in Rust",
    "make a meme generator backend with text overlays in Rust",
    "build a live sports score tracker backend in Rust",
    "generate a book search API with rating filters in Rust",
    "create a calendar API with color-coded events in Rust",
    "build an expense report generator API in Rust",
    "make a file encryption demo in Rust",
    "create a responsive navigation drawer API in Rust",
    "generate a playlist shuffler backend in Rust",
    "design a simple CRM dashboard backend in Rust",
    "write an onboarding wizard backend with tooltips in Rust",
    "produce a recipe ingredient scaler API in Rust",
    "create a random joke API in Rust",
    "build a time tracker API for work tasks in Rust",
    "generate a virtual dice roller CLI in Rust",
    "implement a study timer CLI with break reminders in Rust",
    "write an image compressor backend in Rust",
    "create a live poll voting API in Rust",
    "make a portfolio project grid API with filters in Rust",
    "build a text-to-speech demo in Rust",
    "generate a random color palette generator API in Rust",
    "create a markdown editor backend with preview in Rust",
    "build a responsive testimonial carousel API in Rust",
    "make a simple online whiteboard backend in Rust",
    "create a QR code generator API in Rust",
    "generate a personal budget visualizer API in Rust",
    "design a streaming countdown overlay backend in Rust",
    "write a chessboard renderer API with move highlights in Rust",
    "produce a virtual bookshelf backend with categories in Rust",
    "create a sticky header widget API for scrolling pages in Rust",
    "build a feedback form API with star rating in Rust",
    "generate a contact import/export tool backend in Rust",
    "implement a site uptime monitor in Rust",
    "write a goal-setting app backend with reminders in Rust",
    "create a code challenge leaderboard API in Rust",
    "make a text formatter backend with presets in Rust",
    "build a business hours display API in Rust",
    "generate a classroom attendance checker backend in Rust",
    "create an online raffle draw picker API in Rust",
    "build a flash sale countdown banner API in Rust",
    "make a random team generator backend for events in Rust",
    "create a live visitor counter API for websites in Rust",
    "generate a daily motivational message API in Rust",
    "design a custom alert system backend for forms in Rust",
    "write an API data visualizer backend with charts in Rust",
    "produce a responsive landing page hero section backend in Rust",
    "create a password protected notes API in Rust",
    "build a restaurant menu API with filter options in Rust",
    "generate a shift schedule planner backend in Rust",
    "implement a user registration flow backend with validation in Rust",
]


api = "https://ai.hackclub.com/chat/completions"


def get_code(code):
    m = re.search(r"```(?:rust)?\n(.+?)```", code, flags=re.S)
    if m:
        return m.group(1).strip()
    return code.strip()


for ind, prompt in enumerate(prompts[199:500], start=1):
    payload = {
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a code generator, provide ONLY the final Rust code, don't provide any explanations or notes. Provide comments in the code explaining it."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ]
    }

    try:
        output = requests.post(api, json=payload)
        output.raise_for_status()
        raw = output.json()["choices"][0]["message"]["content"]
    except Exception as e:
        print(e)
        continue

    code = get_code(raw)
    path = f"dataset/rust/ai/{ind}.rs"
    with open(path, "w", encoding="utf-8") as f:
        f.write(code + "\n")
    print(path)
