import os
import google.generativeai as ai
import time
import re

# adding path so its less tedious to change the path
path = "dataset/js/ai"
os.makedirs('dataset/js/ai', exist_ok=True)
ai.configure(api_key="AIzaSyDhyFVGa6E2eP8BMVp0j4P1Du9BGX19VMI")


# generated this using chatgpt, for html this time, i know there was a better way to do this.
prompts = [
    "write a JavaScript todo list web app",
    "generate a weather app using JavaScript",
    "create a JavaScript newsletter signup form",
    "build a contact form with validation in JavaScript",
    "make a snake game in JavaScript",
    "build a memory matching game with JavaScript",
    "create a business landing page using JavaScript for interactivity",
    "generate a calendar widget in JavaScript showing current month",
    "design a feedback form with star ratings using JavaScript",
    "write a survey form with conditional logic in JavaScript",
    "produce an event registration page using JavaScript for input validation",
    "create a donation form with preset and custom amounts in JavaScript",
    "build an appointment scheduler in JavaScript with date and time pickers",
    "generate a ticket booking interface with seat selection using JavaScript",
    "create a restaurant reservation system with JavaScript",
    "write an invoice template that dynamically adds items using JavaScript",
    "implement a pomodoro timer with start, pause, and reset in JavaScript",
    "create a JavaScript countdown timer for events",
    "build a quiz game with questions and score tracking in JavaScript",
    "write a to-do list in JavaScript that persists with localStorage",
    "generate a weather dashboard using JavaScript and an API",
    "create a newsletter signup popup modal in JavaScript",
    "build a contact form with real-time error messages in JavaScript",
    "make a tic-tac-toe game with JavaScript",
    "create a hangman game with vanilla JavaScript",
    "build a landing page for a SaaS business with JS animations",
    "generate a dynamic calendar with event adding in JavaScript",
    "design a feedback form with emoji rating in JS",
    "write a survey form that saves progress using JavaScript",
    "produce an event registration system with confirmation in JavaScript",
    "create a donation form with live total calculation using JS",
    "build an appointment booking app with calendar in JavaScript",
    "generate a concert ticket booking page with JavaScript seat map",
    "implement a hotel reservation system in JavaScript",
    "write an invoice generator with PDF export in JavaScript",
    "create a pomodoro timer with sound alerts in JS",
    "make a stopwatch with laps using JavaScript",
    "build a to-do app with drag-and-drop tasks in JavaScript",
    "generate a weather widget that updates location dynamically in JS",
    "create a newsletter signup with email validation using JavaScript",
    "build a contact form that sends AJAX requests in JavaScript",
    "make a minesweeper game in vanilla JavaScript",
    "build a chessboard with move validation in JavaScript",
    "create a simple business page with a JavaScript FAQ accordion",
    "generate a calendar with holiday highlighting in JavaScript",
    "design a feedback form with progress bar in JS",
    "write a multi-page survey form using JavaScript",
    "produce an event RSVP form with JavaScript email confirmation",
    "create a donation tracker widget in JavaScript",
    "build an appointment reminder system in JavaScript",
    "generate a movie ticket booking app with seat selection in JS",
    "create a restaurant reservation calendar in JavaScript",
    "write an invoice template with editable fields in JavaScript",
    "implement a pomodoro timer with customizable intervals in JS",
    "build a todo list app with priority sorting using JavaScript",
    "generate a weather forecast app with charts in JavaScript",
    "create a newsletter signup that stores emails in localStorage (JavaScript)",
    "build a multi-step contact form in JavaScript",
    "make a sudoku game using JavaScript",
    "create a matching card game with scoring in JavaScript",
    "build a business page with animated counters in JavaScript",
    "generate a calendar with reminders and notifications in JS",
    "design a feedback widget that slides in from the side using JS",
    "write a survey form that exports results to CSV in JavaScript",
    "produce an event registration form with group signup in JavaScript",
    "create a donation progress bar widget in JavaScript",
    "build an appointment booking system with confirmation emails (JS)",
    "generate a festival ticket booking interface in JavaScript",
    "implement a travel reservation app using JavaScript",
    "write an invoice app with recurring billing in JavaScript",
    "create a pomodoro timer with visual progress in JavaScript",
    "make a stopwatch with time split feature using JS",
    "build a todo list with categories and filtering in JavaScript",
    "generate a weather app with location autocomplete using JS",
    "create a newsletter signup with recaptcha in JavaScript",
    "build a contact form with file upload via JS",
    "make a 2048 game implementation in JavaScript",
    "create a business page with JS-powered testimonials carousel",
    "generate a calendar with drag-and-drop events in JavaScript",
    "design a feedback form with photo upload using JavaScript",
    "write a survey builder tool in JavaScript",
    "produce an event ticket QR code generator in JavaScript",
    "create a donation form with recurring options in JS",
    "build an appointment calendar with color-coded slots in JavaScript",
    "generate a conference booking system in JavaScript",
    "implement a rental reservation form with date range in JavaScript",
    "write an invoice summary page with totals and taxes in JS",
    "create a pomodoro timer with daily statistics in JavaScript",
    "make a stopwatch with countdown feature using JavaScript",
    "build a todo list with swipe gestures for mobile in JS",
    "generate a weather app with animated backgrounds in JavaScript",
    "create a newsletter signup form with success animation in JS",
    "build a contact form with map integration in JavaScript",
    "make a memory game with increasing difficulty in JS",
    "create a business portfolio page with filterable projects (JS)",
    "generate a calendar with iCal export in JavaScript",
    "design a feedback form with conditional fields in JS",
    "write a survey analyzer with chart output in JavaScript",
    "produce an event management dashboard in JavaScript",
    "create a donation leaderboard widget in JS",
    "build an appointment scheduler with SMS alerts (JavaScript)",
    "generate a movie reservation app with ratings in JavaScript",
    "implement a spa appointment booking system in JavaScript",
    "write an invoice tracker app with notifications in JS",
    "create a pomodoro timer with dark mode in JavaScript",
    "make a stopwatch with voice start/stop in JS",
    "build a todo list with recurring tasks in JavaScript",
    "generate a weather map viewer in JavaScript",
    "create a newsletter signup integrated with Mailchimp in JS",
    "build a contact form with custom validation rules in JavaScript",
    "make a checkers game in JavaScript",
    "create a business dashboard with live charts in JavaScript",
    "generate a calendar with event color coding in JavaScript",
    "design a feedback survey with star and text input in JS",
    "write a survey form with branching logic using JavaScript",
    "produce an event waitlist signup form in JavaScript",
    "create a donation widget for live streams in JavaScript",
    "build an appointment booking form with Google Calendar sync (JS)",
    "generate a concert ticket reservation app in JavaScript",
    "implement a vacation rental booking calendar in JavaScript",
    "write an invoice dashboard with filtering in JavaScript",
    "create a pomodoro timer that blocks distractions in JS",
    "make a stopwatch that logs times to a file (JavaScript)",
    "build a todo list with color tags using JavaScript",
    "generate a weather forecast notification system in JS",
    "create a newsletter signup with double opt-in logic (JavaScript)",
    "build a contact form with voice input in JavaScript",
    "make a Simon Says game in JavaScript",
    "create a business landing page with JS-powered hero slider",
    "generate a calendar with yearly view toggle in JavaScript",
    "design a feedback form with audio recording in JS",
    "write a survey response visualizer in JavaScript",
    "produce an event organizer dashboard in JavaScript",
    "create a donation summary chart widget in JS",
    "build an appointment system with reminders in JavaScript",
    "generate a cinema ticket booking system in JS",
    "implement a flight reservation calendar in JavaScript",
    "write an invoice creator with logo upload in JavaScript",
    "create a pomodoro timer with motivational quotes in JS",
    "make a stopwatch with theme customization in JavaScript",
    "build a todo list with deadline reminders in JS",
    "generate a weather station dashboard in JavaScript",
    "create a newsletter signup with social login in JS",
    "build a contact form with drag-and-drop file upload in JS",
    "make a battleship game in JavaScript",
    "create a business site with JS-powered navigation menu",
    "generate a calendar with event sharing in JavaScript",
    "design a feedback form with star ratings and comments in JS",
    "write a survey with timed questions in JavaScript",
    "produce an event booking stats dashboard in JavaScript",
    "create a donation button with goal tracking in JS",
    "build an appointment booking app with payment integration (JavaScript)",
    "generate a sports ticket booking app in JavaScript",
    "implement a hostel reservation system in JavaScript",
    "write an invoice with multi-currency support in JavaScript",
    "create a pomodoro timer with motivational sounds in JS",
    "make a stopwatch with lap time export in JavaScript",
    "build a todo list with tag filtering in JS",
    "generate a weather alert notification system in JavaScript",
    "create a newsletter signup with unsubscribe option in JS",
    "build a contact form with phone number validation in JavaScript",
    "make a whack-a-mole game in JavaScript",
    "create a business page with animated reveal sections (JS)",
    "generate a calendar with drag-to-reschedule events in JavaScript",
    "design a feedback survey with NPS rating in JS",
    "write a survey form with progress indicator in JavaScript",
    "produce an event attendee check-in app in JavaScript",
    "create a donation form with payment gateway integration in JS",
    "build an appointment calendar with export to CSV (JavaScript)",
    "generate a theater seat booking page in JavaScript",
    "implement a campsite reservation app in JavaScript",
    "write an invoice with line item collapsing in JavaScript",
    "create a pomodoro timer with productivity graphs in JS",
    "make a stopwatch with history logging in JavaScript",
    "build a todo list with calendar sync in JS",
    "generate a weather app with radar images in JavaScript",
    "create a newsletter signup with welcome email in JS",
    "build a contact form with two-factor authentication in JS",
    "make a crossword puzzle game in JavaScript",
    "create a business page with interactive testimonials (JS)",
    "generate a calendar with invitation emails in JavaScript",
    "design a feedback form with live preview in JS",
    "write a survey form with captcha in JavaScript",
    "produce an event ticket generator with barcode in JavaScript",
    "create a donation leaderboard with avatars in JS",
    "build an appointment form with map integration (JavaScript)",
    "generate a opera ticket booking interface in JavaScript",
    "implement a parking reservation calendar in JavaScript",
    "write an invoice sending tool with email in JavaScript",
    "create a pomodoro timer with user accounts in JS",
    "make a stopwatch with social sharing in JavaScript",
    "build a todo list with multi-user support in JS",
    "generate a weather app with severe weather alerts in JavaScript",
    "create a newsletter signup with GDPR consent in JS",
    "build a contact form that saves data to Firebase (JS)",
    "make a sudoku solver in JavaScript",
    "create a business site with dark/light mode toggle (JS)",
    "generate a calendar with drag-and-drop for mobile in JavaScript",
    "design a feedback collection tool for teams in JS",
    "write a survey with email invitations in JavaScript",
    "produce an event badge generator in JavaScript",
    "create a donation system with monthly/one-time options in JS",
    "build an appointment system with calendar invitations (JavaScript)",
    "generate a sports event ticketing app in JavaScript",
    "implement a room reservation manager in JavaScript",
    "write an invoice generator with template selection in JavaScript",
    "create a pomodoro timer with streak tracking in JS",
    "make a stopwatch with leaderboard in JavaScript",
    "build a todo list with voice commands in JS",
    "generate a weather app with map overlays in JavaScript",
    "create a newsletter signup with SMS verification in JS",
    "build a contact form with reCAPTCHA in JavaScript",
    "make a connect four game in JavaScript",
    "create a business home page with sticky nav in JS",
    "generate a calendar with custom event types in JavaScript",
    "design a feedback widget for e-commerce in JS",
    "write a survey with multiple languages support in JavaScript",
    "produce an event ticket scanner app in JavaScript",
    "create a donation button with recurring payment in JS",
    "build an appointment dashboard with analytics (JavaScript)",
    "generate a travel ticket booking UI in JavaScript",
    "implement a coworking space reservation system in JavaScript",
    "write an invoice manager with search and filter in JavaScript",
    "create a pomodoro timer with desktop notifications in JS",
    "make a stopwatch with split timer in JavaScript",
    "build a todo list with markdown support in JS",
    "generate a weather app with air quality index in JavaScript",
    "create a newsletter signup with custom fields in JS",
    "build a contact form with address autocomplete in JavaScript",
    "make a mastermind game in JavaScript",
    "create a business site with animated logo using JS",
    "generate a calendar with recurring events in JavaScript",
    "design a feedback form for webinars in JS",
    "write a survey with scoring and feedback in JavaScript",
    "produce an event gallery with upload in JavaScript",
    "create a donation form with anonymous option in JS",
    "build an appointment app with timezone support (JavaScript)",
    "generate a train ticket booking form in JavaScript",
    "implement a gym class reservation calendar in JavaScript",
    "write an invoice generator that saves to cloud in JavaScript",
    "create a pomodoro timer with achievements in JS",
    "make a stopwatch with start/stop hotkeys in JavaScript",
    "build a todo list with subtasks and dependencies in JS",
    "generate a weather app with user location in JavaScript",
    "create a newsletter signup landing page in JS",
    "build a contact form with animated placeholders in JavaScript",
    "make a blackjack game in JavaScript",
    "create a business profile page with JS-powered tabs",
    "generate a calendar with drag-to-create events in JavaScript",
    "design a feedback form for mobile apps in JS",
    "write a survey with real-time results in JavaScript",
    "produce an event ticket email sender in JavaScript",
    "create a donation goal widget with animation in JS",
    "build an appointment scheduling form with calendar picker (JavaScript)",
    "generate a bus ticket booking UI in JavaScript",
    "implement a hotel room reservation calendar in JavaScript",
    "write an invoice template with multi-language support in JavaScript",
    "create a pomodoro timer with focus music in JS",
    "make a stopwatch with progress bar in JavaScript",
    "build a todo list app with notifications in JS",
    "generate a weather app with chart.js for graphs in JavaScript",
    "create a newsletter signup with multiple lists in JS",
    "build a contact form with country dropdown in JavaScript",
    "make a minesweeper game with timer in JavaScript",
    "create a business about page with animated team bios (JS)",
    "generate a calendar with reminders via SMS in JavaScript",
    "design a feedback popup for checkout pages in JS",
    "write a survey with API integration in JavaScript",
    "produce an event schedule manager in JavaScript",
    "create a donation form with progress tracker in JS",
    "build an appointment request app with admin panel (JavaScript)",
    "generate a student ticket booking app in JavaScript",
    "implement a library reservation system in JavaScript",
    "write an invoice generator with barcode in JavaScript",
    "create a pomodoro timer with social sharing in JS",
    "make a stopwatch with voice output in JavaScript",
    "build a todo list with calendar event export in JS",
    "generate a weather trend analyzer in JavaScript",
    "create a newsletter signup with referral tracking in JS",
    "build a contact form that logs messages to Google Sheets (JS)",
    "make a wordle clone game in JavaScript",
    "create a business FAQ page with JS toggle sections",
    "generate a calendar widget with drag-and-drop in JavaScript",
    "design a feedback system for online courses in JS",
    "write a survey builder with save/resume in JavaScript",
    "produce an event ticket PDF generator in JavaScript",
    "create a donation receipt email sender in JS",
    "build an appointment sync tool for Google Calendar (JavaScript)",
    "generate a music ticket booking system in JavaScript",
    "implement a coworking desk reservation in JavaScript",
    "write an invoice generator with digital signature in JavaScript",
    "create a pomodoro timer with voice commands in JS",
    "make a stopwatch that saves sessions in JavaScript",
    "build a todo list with import/export tasks in JS",
    "generate a weather alert app with push notifications in JavaScript",
    "create a newsletter signup form with A/B testing in JS",
    "build a contact form with spam protection in JavaScript",
    "make a sudoku puzzle generator in JavaScript",
    "create a business gallery page with image zoom in JS",
    "generate a calendar with Google sync in JavaScript",
    "design a feedback collection widget for websites in JS",
    "write a survey form with printable results in JavaScript",
    "produce an event RSVP manager in JavaScript",
    "create a donation form with preset tiers in JS",
    "build an appointment reminder app with SMS support (JavaScript)",
    "generate an airline ticket booking app in JavaScript",
    "implement a restaurant table reservation calendar in JavaScript",
    "write an invoice dashboard with analytics in JavaScript",
    "create a pomodoro timer with different sound themes in JS",
    "make a stopwatch with animated digits in JavaScript",
    "build a todo list with recurring reminders in JS",
    "generate a weather forecast comparison tool in JavaScript",
]

def get_code(code):
    m = re.search(r"```(?:javascript)?\n(.+?)```", code, flags=re.S)
    if m:
        return m.group(1).strip()
    return code.strip()

model = ai.GenerativeModel('gemini-1.5-flash')

for ind, prompt in enumerate(prompts[144:501], start=145):
    try:
        combined_prompt = """You are a code generator, provide ONLY the final JavaScript code, dont provide any explanations, or notes. provide comments in the code explaining it. User Request: """ + prompt
        
        # time.sleep(1)

        response = model.generate_content(combined_prompt)
        raw = response.text

        code = get_code(raw)

        path = f"dataset/js/ai/{ind}.js"

        with open(path, "w", encoding="utf-8") as f:
            f.write(code + '\n')

        print(path)

    except Exception as e:
        print(e)
        continue