import os
import google.generativeai as ai
import time
import re


os.makedirs('dataset/html/ai', exist_ok=True)



# generated this using chatgpt, for html this time, i know there was a better way to do this.

prompts = [
    "write an HTML file for a to-do list web app",
    "generate a portfolio webpage in HTML",
    "create an HTML file for a terminal interface simulation",
    "generate an HTML homepage for a web operating system concept",
    "write an HTML file for a simple web server status page",
    "design an HTML contact form with name, email, and message fields",
    "produce an HTML image gallery showcasing six sample images",
    "create an HTML recipe page with ingredients and instructions",
    "write an HTML file for a login page with username and password inputs",
    "generate an HTML movie list page displaying five movies with posters",
    "build an HTML newsletter signup form with email input",
    "create an HTML file for a simple snake game layout",
    "write an HTML landing page for a business website with a hero section",
    "produce an HTML calendar widget showing the current month",
    "design an HTML feedback form with star rating and comments field",
    "generate an HTML survey form with multiple-choice and open-ended questions",
    "create an HTML event registration page with attendee details and event selection",
    "build an HTML donation form with preset and custom amount inputs",
    "write an HTML appointment scheduler with date and time selection",
    "generate an HTML ticket booking page with event listings and seat selection",
    "create an HTML blog homepage with recent posts and sidebar",
    "design an HTML single blog post page with comments section",
    "write an HTML FAQ page with collapsible answers",
    "generate an HTML pricing table for three subscription tiers",
    "build an HTML contact us page with embedded Google map",
    "produce an HTML 404 error page with a search bar",
    "create an HTML product listing page for an online shop",
    "write an HTML shopping cart page with item quantity selectors",
    "generate an HTML checkout form with billing and shipping address fields",
    "design an HTML thank you page for successful order submission",
    "create an HTML team members page with profile cards",
    "write an HTML timeline for a project’s milestones",
    "build an HTML testimonial slider with three reviews",
    "generate an HTML about us page with company history",
    "produce an HTML careers page with job application form",
    "design an HTML press release page with media contact info",
    "create an HTML privacy policy page with collapsible sections",
    "write an HTML terms and conditions page formatted for readability",
    "generate an HTML sitemap with links to all major pages",
    "build an HTML newsletter archive page with links to previous editions",
    "create an HTML weather dashboard with temperature and forecast",
    "write an HTML calculator with number and operator buttons",
    "generate an HTML unit converter for metric and imperial systems",
    "design an HTML currency converter with dropdowns for currencies",
    "produce an HTML BMI calculator with input fields and result display",
    "build an HTML stopwatch with start, stop, and reset buttons",
    "create an HTML countdown timer for an event",
    "write an HTML random quote generator with refresh button",
    "generate an HTML password strength checker with real-time feedback",
    "design an HTML palindrome checker with input and result",
    "create an HTML trivia quiz with multiple choice questions",
    "write an HTML flashcards study tool with flip animation",
    "generate an HTML math worksheet with questions and answer key",
    "build an HTML periodic table of elements with clickable cells",
    "produce an HTML vocabulary builder with word and definition pairs",
    "design an HTML crossword puzzle grid",
    "create an HTML word search puzzle with hidden word list",
    "write an HTML memory matching game with cards",
    "generate an HTML hangman game with letter guesses",
    "build an HTML tic-tac-toe game board",
    "create an HTML chessboard with clickable squares",
    "write an HTML sudoku puzzle generator",
    "generate an HTML checkers game layout",
    "design an HTML connect four game board",
    "produce an HTML minesweeper grid",
    "build an HTML color picker tool",
    "create an HTML drawing canvas",
    "write an HTML paint app with color palette",
    "generate an HTML pixel art maker",
    "design an HTML photo editor with brightness and contrast sliders",
    "create an HTML resume template with sections for skills and experience",
    "write an HTML cover letter template",
    "generate an HTML job application form",
    "build an HTML interview scheduler",
    "produce an HTML job board listing",
    "design an HTML employee directory",
    "create an HTML payroll calculator",
    "write an HTML shift schedule calendar",
    "generate an HTML time-off request form",
    "build an HTML expense report submission form",
    "create an HTML classroom attendance sheet",
    "write an HTML lesson plan template",
    "generate an HTML gradebook for teachers",
    "build an HTML student profile page",
    "produce an HTML online homework submission form",
    "design an HTML parent-teacher conference scheduler",
    "create an HTML academic calendar",
    "write an HTML course registration form",
    "generate an HTML school lunch menu",
    "build an HTML teacher evaluation form",
    "create an HTML sports team roster",
    "write an HTML event flyer for a school fundraiser",
    "generate an HTML science fair project submission page",
    "build an HTML art gallery for student work",
    "produce an HTML music recital program",
    "design an HTML book review page",
    "create an HTML library catalog search",
    "write an HTML reading log template",
    "generate an HTML summer camp registration form",
    "build an HTML camp activities schedule",
    "create an HTML packing list for campers",
    "write an HTML activity sign-up sheet",
    "generate an HTML parent information page",
    "build an HTML camp counselor bios page",
    "produce an HTML safety rules checklist",
    "design an HTML awards ceremony program",
    "create an HTML lost and found submission form",
    "write an HTML camp map with locations",
    "generate an HTML movie night schedule",
    "build an HTML scavenger hunt clue list",
    "create an HTML leaderboard for camp games",
    "write an HTML daily weather update page",
    "generate an HTML emergency contact form",
    "build an HTML packing tips article",
    "produce an HTML volunteer sign-up form",
    "design an HTML camp newsletter archive",
    "create an HTML registration confirmation page",
    "write an HTML fee payment form",
    "generate an HTML camp feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for campers",
    "write an HTML field trip permission form",
    "generate an HTML parent volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive",
    "create an HTML trip registration confirmation",
    "write an HTML trip fee payment form",
    "generate an HTML trip feedback survey",
    "build an HTML trip itinerary page",
    "create an HTML bus list for trip attendees",
    "write an HTML trip permission form",
    "generate an HTML trip volunteer application",
    "build an HTML trip checklist",
    "produce an HTML trip summary report",
    "design an HTML trip photo gallery",
    "create an HTML trip schedule calendar",
    "write an HTML thank you page for trip volunteers",
    "generate an HTML trip evaluation form",
    "build an HTML lost item report form",
    "create an HTML found item submission page",
    "write an HTML trip packing list",
    "generate an HTML trip rules reminder page",
    "build an HTML trip map with destinations",
    "create an HTML driver contact list",
    "write an HTML emergency procedures page",
    "generate an HTML trip highlights article",
    "build an HTML trip feedback form",
    "create an HTML trip end-of-day summary",
    "write an HTML trip awards ceremony program",
    "generate an HTML trip lost & found page",
    "build an HTML trip newsletter archive"
]


def get_code(code):
    m = re.search(r"```(?:python)?\n(.+?)```", code, flags=re.S)
    if m:
        return m.group(1).strip()
    return code.strip()

model = ai.GenerativeModel('gemini-1.5-flash')

for ind, prompt in enumerate(prompts[165:501], start=165):
    try:
        combined_prompt = """You are a code generator, provide ONLY the final HTML code, dont provide any explanations, or notes. provide comments in the code explaining it. User Request: """ + prompt
        
        # time.sleep(1)

        response = model.generate_content(combined_prompt)
        raw = response.text

        code = get_code(raw)

        path = f"dataset/html/ai/{ind}.html"

        with open(path, "w", encoding="utf-8") as f:
            f.write(code + '\n')

        print(path)

    except Exception as e:
        print(e)
        continue